// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idemixmsp/msp_config.proto

package idemixmsp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IdemixMSPConfig struct {
	// Name holds the identifier of the MSP
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ipk represents the (serialized) issuer public key
	Ipk []byte `protobuf:"bytes,2,opt,name=ipk,proto3" json:"ipk,omitempty"`
	// signer may contain crypto material to configure a default signer
	Signer *IdemixMSPSignerConfig `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	// revocation_pk is the public key used for revocation of credentials
	RevocationPk []byte `protobuf:"bytes,4,opt,name=revocation_pk,json=revocationPk,proto3" json:"revocation_pk,omitempty"`
	// epoch represents the current epoch (time interval) used for revocation
	Epoch int64 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// curve_id indicates which Elliptic Curve should be used
	CurveId string `protobuf:"bytes,6,opt,name=curve_id,json=curveId,proto3" json:"curve_id,omitempty"`
	// schema contains the version of the schema used by this credential
	Schema               string   `protobuf:"bytes,7,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdemixMSPConfig) Reset()         { *m = IdemixMSPConfig{} }
func (m *IdemixMSPConfig) String() string { return proto.CompactTextString(m) }
func (*IdemixMSPConfig) ProtoMessage()    {}
func (*IdemixMSPConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_783ba658a7862c73, []int{0}
}

func (m *IdemixMSPConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdemixMSPConfig.Unmarshal(m, b)
}
func (m *IdemixMSPConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdemixMSPConfig.Marshal(b, m, deterministic)
}
func (m *IdemixMSPConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdemixMSPConfig.Merge(m, src)
}
func (m *IdemixMSPConfig) XXX_Size() int {
	return xxx_messageInfo_IdemixMSPConfig.Size(m)
}
func (m *IdemixMSPConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IdemixMSPConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IdemixMSPConfig proto.InternalMessageInfo

func (m *IdemixMSPConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IdemixMSPConfig) GetIpk() []byte {
	if m != nil {
		return m.Ipk
	}
	return nil
}

func (m *IdemixMSPConfig) GetSigner() *IdemixMSPSignerConfig {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *IdemixMSPConfig) GetRevocationPk() []byte {
	if m != nil {
		return m.RevocationPk
	}
	return nil
}

func (m *IdemixMSPConfig) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *IdemixMSPConfig) GetCurveId() string {
	if m != nil {
		return m.CurveId
	}
	return ""
}

func (m *IdemixMSPConfig) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

// IdemixMSPSIgnerConfig contains the crypto material to set up an idemix signing identity
type IdemixMSPSignerConfig struct {
	// cred represents the serialized idemix credential of the default signer
	Cred []byte `protobuf:"bytes,1,opt,name=cred,proto3" json:"cred,omitempty"`
	// sk is the secret key of the default signer, corresponding to credential Cred
	Sk []byte `protobuf:"bytes,2,opt,name=sk,proto3" json:"sk,omitempty"`
	// organizational_unit_identifier defines the organizational unit the default signer is in
	OrganizationalUnitIdentifier string `protobuf:"bytes,3,opt,name=organizational_unit_identifier,json=organizationalUnitIdentifier,proto3" json:"organizational_unit_identifier,omitempty"`
	// role defines whether the default signer is admin, peer, member or client
	Role int32 `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	// enrollment_id contains the enrollment id of this signer
	EnrollmentId string `protobuf:"bytes,5,opt,name=enrollment_id,json=enrollmentId,proto3" json:"enrollment_id,omitempty"`
	// credential_revocation_information contains a serialized CredentialRevocationInformation
	CredentialRevocationInformation []byte `protobuf:"bytes,6,opt,name=credential_revocation_information,json=credentialRevocationInformation,proto3" json:"credential_revocation_information,omitempty"`
	// RevocationHandle is the handle used to single out this credential and determine its revocation status
	RevocationHandle string `protobuf:"bytes,7,opt,name=revocation_handle,json=revocationHandle,proto3" json:"revocation_handle,omitempty"`
	// curve_id indicates which Elliptic Curve should be used
	CurveId string `protobuf:"bytes,8,opt,name=curve_id,json=curveId,proto3" json:"curve_id,omitempty"`
	// schema contains the version of the schema used by this credential
	Schema               string   `protobuf:"bytes,9,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdemixMSPSignerConfig) Reset()         { *m = IdemixMSPSignerConfig{} }
func (m *IdemixMSPSignerConfig) String() string { return proto.CompactTextString(m) }
func (*IdemixMSPSignerConfig) ProtoMessage()    {}
func (*IdemixMSPSignerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_783ba658a7862c73, []int{1}
}

func (m *IdemixMSPSignerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdemixMSPSignerConfig.Unmarshal(m, b)
}
func (m *IdemixMSPSignerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdemixMSPSignerConfig.Marshal(b, m, deterministic)
}
func (m *IdemixMSPSignerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdemixMSPSignerConfig.Merge(m, src)
}
func (m *IdemixMSPSignerConfig) XXX_Size() int {
	return xxx_messageInfo_IdemixMSPSignerConfig.Size(m)
}
func (m *IdemixMSPSignerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IdemixMSPSignerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IdemixMSPSignerConfig proto.InternalMessageInfo

func (m *IdemixMSPSignerConfig) GetCred() []byte {
	if m != nil {
		return m.Cred
	}
	return nil
}

func (m *IdemixMSPSignerConfig) GetSk() []byte {
	if m != nil {
		return m.Sk
	}
	return nil
}

func (m *IdemixMSPSignerConfig) GetOrganizationalUnitIdentifier() string {
	if m != nil {
		return m.OrganizationalUnitIdentifier
	}
	return ""
}

func (m *IdemixMSPSignerConfig) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *IdemixMSPSignerConfig) GetEnrollmentId() string {
	if m != nil {
		return m.EnrollmentId
	}
	return ""
}

func (m *IdemixMSPSignerConfig) GetCredentialRevocationInformation() []byte {
	if m != nil {
		return m.CredentialRevocationInformation
	}
	return nil
}

func (m *IdemixMSPSignerConfig) GetRevocationHandle() string {
	if m != nil {
		return m.RevocationHandle
	}
	return ""
}

func (m *IdemixMSPSignerConfig) GetCurveId() string {
	if m != nil {
		return m.CurveId
	}
	return ""
}

func (m *IdemixMSPSignerConfig) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func init() {
	proto.RegisterType((*IdemixMSPConfig)(nil), "idemixmsp.IdemixMSPConfig")
	proto.RegisterType((*IdemixMSPSignerConfig)(nil), "idemixmsp.IdemixMSPSignerConfig")
}

func init() { proto.RegisterFile("idemixmsp/msp_config.proto", fileDescriptor_783ba658a7862c73) }

var fileDescriptor_783ba658a7862c73 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xd1, 0x8a, 0x13, 0x31,
	0x14, 0x65, 0xa6, 0xdb, 0xee, 0x4e, 0x9c, 0x5d, 0xd7, 0xe0, 0xca, 0x28, 0xe2, 0x8e, 0xeb, 0x4b,
	0x41, 0x68, 0x41, 0x5f, 0x7c, 0xae, 0x82, 0x46, 0x28, 0x0c, 0x59, 0x84, 0x45, 0x84, 0x21, 0x9b,
	0xa4, 0x6d, 0xe8, 0x24, 0x19, 0x32, 0xe9, 0x22, 0x3e, 0xfb, 0x25, 0x3e, 0xfa, 0x29, 0xfe, 0x84,
	0xe0, 0x83, 0x0f, 0x7e, 0x85, 0xe4, 0xb6, 0x3b, 0x33, 0x05, 0x7d, 0x3b, 0xf7, 0xde, 0x93, 0x93,
	0x7b, 0x0e, 0x17, 0x3d, 0x52, 0x42, 0x6a, 0xf5, 0x59, 0x37, 0xf5, 0x54, 0x37, 0x75, 0xc9, 0xad,
	0x59, 0xa8, 0xe5, 0xa4, 0x76, 0xd6, 0x5b, 0x9c, 0xb4, 0xb3, 0x8b, 0x9f, 0x11, 0xba, 0x4b, 0xa0,
	0x9a, 0x5f, 0x16, 0xaf, 0x81, 0x84, 0x31, 0x3a, 0x30, 0x4c, 0xcb, 0x2c, 0xca, 0xa3, 0x71, 0x42,
	0x01, 0xe3, 0x53, 0x34, 0x50, 0xf5, 0x3a, 0x8b, 0xf3, 0x68, 0x9c, 0xd2, 0x00, 0xf1, 0x2b, 0x34,
	0x6a, 0xd4, 0xd2, 0x48, 0x97, 0x0d, 0xf2, 0x68, 0x7c, 0xe7, 0x45, 0x3e, 0x69, 0x55, 0x27, 0xad,
	0xe2, 0x25, 0x30, 0xb6, 0xba, 0x74, 0xc7, 0xc7, 0xcf, 0xd0, 0xb1, 0x93, 0x37, 0x96, 0x33, 0xaf,
	0xac, 0x29, 0xeb, 0x75, 0x76, 0x00, 0xaa, 0x69, 0xd7, 0x2c, 0xd6, 0xf8, 0x3e, 0x1a, 0xca, 0xda,
	0xf2, 0x55, 0x36, 0xcc, 0xa3, 0xf1, 0x80, 0x6e, 0x0b, 0xfc, 0x10, 0x1d, 0xf1, 0x8d, 0xbb, 0x91,
	0xa5, 0x12, 0xd9, 0x08, 0xd6, 0x3b, 0x84, 0x9a, 0x08, 0xfc, 0x00, 0x8d, 0x1a, 0xbe, 0x92, 0x9a,
	0x65, 0x87, 0x30, 0xd8, 0x55, 0x17, 0xbf, 0x63, 0x74, 0xf6, 0xcf, 0x7d, 0x82, 0x4f, 0xee, 0xa4,
	0x00, 0x9f, 0x29, 0x05, 0x8c, 0x4f, 0x50, 0xdc, 0xdc, 0xda, 0x8c, 0x9b, 0x35, 0x7e, 0x83, 0x9e,
	0x58, 0xb7, 0x64, 0x46, 0x7d, 0x81, 0xc5, 0x58, 0x55, 0x6e, 0x8c, 0xf2, 0xa5, 0x12, 0xd2, 0x78,
	0xb5, 0x50, 0x3b, 0xf7, 0x09, 0x7d, 0xbc, 0xcf, 0xfa, 0x60, 0x94, 0x27, 0x2d, 0x27, 0xfc, 0xe4,
	0x6c, 0x25, 0xc1, 0xe8, 0x90, 0x02, 0x0e, 0x29, 0x48, 0xe3, 0x6c, 0x55, 0x69, 0x69, 0x82, 0x20,
	0x18, 0x4d, 0x68, 0xda, 0x35, 0x89, 0xc0, 0xef, 0xd1, 0xd3, 0xb0, 0x56, 0x10, 0x62, 0x55, 0xd9,
	0x4b, 0x4d, 0x99, 0x85, 0x75, 0x1a, 0x30, 0x04, 0x91, 0xd2, 0xf3, 0x8e, 0x48, 0x5b, 0x1e, 0xe9,
	0x68, 0xf8, 0x39, 0xba, 0xd7, 0x13, 0x58, 0x31, 0x23, 0x2a, 0xb9, 0xcb, 0xea, 0xb4, 0x1b, 0xbc,
	0x83, 0xfe, 0x5e, 0xd0, 0x47, 0xff, 0x0b, 0x3a, 0xe9, 0x07, 0x3d, 0xfb, 0x1a, 0xa1, 0x63, 0x6e,
	0x75, 0x77, 0x06, 0xb3, 0x93, 0x79, 0x53, 0x6f, 0xb3, 0x2e, 0xc2, 0xdd, 0x15, 0xd1, 0xc7, 0xf3,
	0xa5, 0xf2, 0xab, 0xcd, 0xf5, 0x84, 0x5b, 0x3d, 0x25, 0xb3, 0xf9, 0x74, 0xcb, 0x9d, 0xb6, 0x4f,
	0xbe, 0xc5, 0x03, 0x72, 0x75, 0xf5, 0x3d, 0x4e, 0xc8, 0x6d, 0xe7, 0x47, 0x0f, 0xff, 0x8a, 0xcf,
	0x5a, 0xfc, 0xe9, 0x6d, 0x31, 0x9b, 0x4b, 0xcf, 0x04, 0xf3, 0xec, 0x4f, 0x8f, 0x73, 0x3d, 0x82,
	0x1b, 0x7f, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x60, 0x94, 0x5d, 0xb8, 0x01, 0x03, 0x00, 0x00,
}
