// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bccsp/schemes/aries/cred.proto

package aries

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Credential specifies a credential object
type Credential struct {
	Cred                 []byte   `protobuf:"bytes,1,opt,name=cred,proto3" json:"cred,omitempty"`
	Attrs                [][]byte `protobuf:"bytes,2,rep,name=attrs,proto3" json:"attrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credential) Reset()         { *m = Credential{} }
func (m *Credential) String() string { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()    {}
func (*Credential) Descriptor() ([]byte, []int) {
	return fileDescriptor_57701eac61520cf0, []int{0}
}

func (m *Credential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credential.Unmarshal(m, b)
}
func (m *Credential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credential.Marshal(b, m, deterministic)
}
func (m *Credential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credential.Merge(m, src)
}
func (m *Credential) XXX_Size() int {
	return xxx_messageInfo_Credential.Size(m)
}
func (m *Credential) XXX_DiscardUnknown() {
	xxx_messageInfo_Credential.DiscardUnknown(m)
}

var xxx_messageInfo_Credential proto.InternalMessageInfo

func (m *Credential) GetCred() []byte {
	if m != nil {
		return m.Cred
	}
	return nil
}

func (m *Credential) GetAttrs() [][]byte {
	if m != nil {
		return m.Attrs
	}
	return nil
}

// Signature is a PoK of a BBS+ signature (a credential)
type Signature struct {
	MainSignature        []byte   `protobuf:"bytes,1,opt,name=main_signature,json=mainSignature,proto3" json:"main_signature,omitempty"`
	NymCommit            []byte   `protobuf:"bytes,2,opt,name=nym_commit,json=nymCommit,proto3" json:"nym_commit,omitempty"`
	NymProof             []byte   `protobuf:"bytes,3,opt,name=nym_proof,json=nymProof,proto3" json:"nym_proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_57701eac61520cf0, []int{1}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetMainSignature() []byte {
	if m != nil {
		return m.MainSignature
	}
	return nil
}

func (m *Signature) GetNymCommit() []byte {
	if m != nil {
		return m.NymCommit
	}
	return nil
}

func (m *Signature) GetNymProof() []byte {
	if m != nil {
		return m.NymProof
	}
	return nil
}

func init() {
	proto.RegisterType((*Credential)(nil), "aries.Credential")
	proto.RegisterType((*Signature)(nil), "aries.Signature")
}

func init() { proto.RegisterFile("bccsp/schemes/aries/cred.proto", fileDescriptor_57701eac61520cf0) }

var fileDescriptor_57701eac61520cf0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xd9, 0xd4, 0x8a, 0x1d, 0x56, 0xc1, 0xe0, 0xa1, 0x20, 0xca, 0xb2, 0x20, 0xac, 0x97,
	0xe6, 0x20, 0x78, 0xdf, 0xee, 0x41, 0x3c, 0x2c, 0x94, 0xf5, 0xb2, 0x88, 0x50, 0xd2, 0x34, 0xee,
	0x06, 0x9c, 0xa4, 0x24, 0x29, 0xd8, 0xd7, 0xf1, 0xe8, 0xa3, 0xf8, 0x18, 0x1e, 0x7d, 0x0a, 0x49,
	0xac, 0x78, 0xf1, 0x34, 0xf9, 0xbe, 0xf9, 0x09, 0x33, 0x03, 0x97, 0x8d, 0x10, 0xae, 0x63, 0x4e,
	0xec, 0x25, 0x4a, 0xc7, 0xb8, 0x55, 0xd2, 0x31, 0x61, 0x65, 0x5b, 0x74, 0xd6, 0x78, 0x43, 0xd3,
	0x68, 0xe6, 0xb7, 0x00, 0x2b, 0x2b, 0x5b, 0xa9, 0xbd, 0xe2, 0x2f, 0x94, 0xc2, 0x41, 0x88, 0xe4,
	0x93, 0xd9, 0x64, 0x31, 0xdd, 0xc4, 0x37, 0x3d, 0x83, 0x94, 0x7b, 0x6f, 0x5d, 0x4e, 0x66, 0xc9,
	0x62, 0xba, 0xf9, 0x81, 0xb9, 0x86, 0xec, 0x41, 0xed, 0x34, 0xf7, 0xbd, 0x95, 0xf4, 0x0a, 0x4e,
	0x90, 0x2b, 0x5d, 0xbb, 0x5f, 0x33, 0x7e, 0x70, 0x1c, 0xec, 0x5f, 0xec, 0x02, 0x40, 0x0f, 0x58,
	0x0b, 0x83, 0xa8, 0x7c, 0x4e, 0x62, 0x24, 0xd3, 0x03, 0xae, 0xa2, 0xa0, 0xe7, 0x10, 0xa0, 0xee,
	0xac, 0x31, 0xcf, 0x79, 0x12, 0xbb, 0x47, 0x7a, 0xc0, 0x2a, 0x70, 0xd9, 0x43, 0x26, 0x0c, 0x16,
	0x71, 0xe8, 0x32, 0x0b, 0x23, 0x57, 0x61, 0x8d, 0x6a, 0xf2, 0x78, 0xbd, 0x53, 0x7e, 0xdf, 0x37,
	0x85, 0x30, 0xc8, 0xee, 0xcb, 0x35, 0x53, 0xad, 0x44, 0xf5, 0xca, 0xfe, 0x59, 0xff, 0x8d, 0x24,
	0xcb, 0xed, 0xf6, 0x9d, 0xa4, 0xcb, 0x40, 0x1f, 0x63, 0xfd, 0x24, 0xa7, 0xb1, 0x3e, 0xdd, 0x55,
	0xe5, 0x5a, 0x7a, 0xde, 0x72, 0xcf, 0xbf, 0xc6, 0x5e, 0x73, 0x18, 0x8f, 0x75, 0xf3, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x9f, 0xd1, 0xb6, 0x8d, 0x4e, 0x01, 0x00, 0x00,
}
